properties(
    [[$class: 'BuildDiscarderProperty',strategy: 
     [$class: 'LogRotator', numToKeepStr: '10']],
      pipelineTriggers([pollSCM('H/2 * * * *')]),]
)
pipeline {
    agent any

    stages {
        // stage('Thunder_Image_Build') {
        //     steps {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'alpine_build']], doGenerateSubmoduleConfigurations: false,
                        extensions: [[$class: 'CloneOption', timeout: 10, noTags: true, shallow: false]]
                                    +[[$class: 'LocalBranch', localBranch: '']],
                        submoduleCfg: [], userRemoteConfigs: [[refspec: 'master', url: "${PS_GIT_URI}"]]])
            }
        }
    }
}
