pipeline {
    agent any
    stages {
      stage('Build_Alpine_Thunder_image') {
        steps {
            openshiftBuild(namespace: 'thunder', buildConfig: 'thunder-alpine', showBuildLogs: 'true',  waitTime: '3000000')
          }
        }
      stage('Deploy Thunder') {
        steps {
          sh "echo 123"
        }
      }
    }
}
