  
properties(
    [[$class: 'BuildDiscarderProperty',strategy: 
     [$class: 'LogRotator', numToKeepStr: '10']],
      pipelineTriggers([pollSCM('H/5 * * * *')]),]
)
pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                /* `make check` returns non-zero on test failures,
                * using `true` to allow the Pipeline to continue nonetheless
                */
                echo "333" 
                echo "123" 
            }
        }
        stage('Approve for Deployment') {
            input message: 'Deploy Thunder APP?',
            id: 'approval'
        }
    }
}
